server:
  port: 10010

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    nacos: # nacos
      server-addr: 192.168.154.132:8848
    gateway:
      #      discovery:
      #        locator:
      #          enabled: true # 开启了会自动匹配路由规则
      routes:
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/douyin/user/**
        - id: user-service
          uri: lb://interaction
          predicates:
            - Path=/douyin/favorite/**,/douyin/comment/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: fatal # gateway 日志打印级别

dubbo:
  application:
    name: dubbo-gateway # 应用名
  protocol:
    name: dubbo # dubbo 协议
    port: 20880 # 协议端口
  registry:
    id: nacos-gateway
    address: nacos://192.168.154.132:8848 # 注册地址
  config-center:
    timeout: 10000